<?php 

require 'conexao.php';


//busca das cidades 
$sql_all = 'SELECT * FROM cidades WHERE id_uf = 42';
$res_all = $conexao->prepare( $sql_all );
$res_all->execute();


$total_registros = $res_all->rowCount();

?>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <!-- <meta http-equiv='refresh' content='5'> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
	  

    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   
   <script src="scripts.js" defer></script>

   <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
        }

        .n1 {
            height: 10%;
        }
        .n2 {
            height: 80%;
        }
        [class^="col-"] {
            border: 1px solid red;
        }
        img {
            height: 100%;
            width: 100%;
            object-fit: cover;
        }
   </style>
</head>
<body>
    <div class="container">
       
        <div class="d-grid gap-2 col-6 mx-auto">
           
            <button id="generate-pdf" class="btn btn-lg btn-success" >Gerar PDF</button>
        </div>
        <div id="html_footer">
            <p style="text-align:center;">Page <span class="page"></span> of <span class="total"></span>
            </p>

        </div>
        <div id="html_header">
            <!-- new Date().toLocaleDateString()  -->

            <p style="text-align:center;">Generated by my app on </p>

        </div>
        <div id="informacoes">
            <p>Melhorias: https://pspdfkit.com/blog/2023/how-to-convert-html-to-pdf-using-html2pdf/</p>

            <p>Ver est outro vidoe,  parece mais elegante</p>
            <p>https://www.youtube.com/watch?v=DV2tAG5E-F0</p>
        </div>
       
        <div id="content">
            <h1>Olá Mundo</h1>
            <p>Este será o conteudo do PDF!</p>

            
            <div class="col-12 ml-2">
                <!-- <h3 class="">Ultimas Notícias</h3> -->
                <div class="card center">
                    <div class="row">
                        <!-- <div class="col-2"></div> -->
                        <div class="col-2">                           
                            <img src="img/sol_mar.jpg" class="w-100 img-thumbnail"   >
                        </div>
                        <div class="col-10 ">
                            <div class="">
                                <h1 class=" text-center">Titulo do Relatório </h1>
                                <h2 class=" text-center">Sub tiulo do relatorio </h2>
                                <h3 class=" text-center">Terceira linha  </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- <div class=" container-fluid border  border-success p-2" style="--bs-border-opacity: .5;" >
                <img src="img/sol_mar.jpg"  class="img-thumbnail float-start " alt="" width="50%" height="150px">
                <h1 class=" text-center">Titulo do Relatório </h1>
                <h2 class=" text-center">Sub tiulo do relatorio </h2>
                <h3 class=" text-center">Terceira linha  </h3>
                <h4 class=" text-center">Ultima linha  </h4>                
            </div> -->

            <table style="width: 100%; border-collapse: collapse;" border="0">
                <tbody>
                <tr>
                <td style="width: 50%;">%url</td>
                <td style="width: 50%; text-align: right;"><div class="lastpage">%page</div></td>
                </tr>
                </tbody>
                </table>

            <div>
                <p>Classes da imagem class="img-thumbnail float-start " alt="" width="50%" height="150px" </p>
                <p>classe do cabeçalho:" border border-success p-2" border-success p-2 mb-2 </p>
                <p>classes das imagnes  img-thumbnail float-start img-fluid  rounded float-start </p>
                <p>Classes do Titulo:p-5 my-5 bg-dark text-white </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem beatae odit id quo et expedita possimus a quam iusto assumenda[aqui desaparece], tempora, repellendus distinctio eligendi laboriosam delectus doloribus quis, velit nostrum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem beatae odit id quo et expedita possimus a quam iusto assumenda, tempora, repellendus distinctio eligendi laboriosam delectus doloribus quis, velit nostrum.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem beatae odit id quo et expedita possimus a quam iusto assumenda, tempora, repellendus distinctio eligendi laboriosam delectus doloribus quis, velit nostrum.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem beatae odit id quo et expedita possimus a quam iusto assumenda, tempora, repellendus distinctio eligendi laboriosam delectus doloribus quis, velit nostrum.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem beatae odit id quo et expedita possimus a quam iusto assumenda, tempora, repellendus distinctio eligendi laboriosam delectus doloribus quis, velit nostrum.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem beatae odit id quo et expedita possimus a quam iusto assumenda, tempora, repellendus distinctio eligendi laboriosam delectus doloribus quis, velit nostrum.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem beatae odit id quo et expedita possimus a quam iusto assumenda, tempora, repellendus distinctio eligendi laboriosam delectus doloribus quis, velit nostrum.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem beatae odit id quo et expedita possimus a quam iusto assumenda, tempora, repellendus distinctio eligendi laboriosam delectus doloribus quis, velit nostrum.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem beatae odit id quo et expedita possimus a quam iusto assumenda, tempora, repellendus distinctio eligendi laboriosam delectus doloribus quis, velit nostrum.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem beatae odit id quo et expedita possimus a quam iusto assumenda, tempora, repellendus distinctio eligendi laboriosam delectus doloribus quis, velit nostrum.
                </p>
            </div>

            <!-- <div class="col-12 ml-2 bg-secondary">
                <h3 class="">Ultimas Notícias</h3>
                <div class="card">
                    <div class="row">
                        <div class="col-3 bg-dark imagem" style="background:url(https://www.cleverfiles.com/howto/wp-content/uploads/2016/08/mini.jpg) center;">
                        </div>
                        <div class="col-9">
                            <div class="card-block">
                                <div class="card-title font-weight-bold mb-1 text-center">
                                    <h1> Lorem ipsum dolor sit amet</h1>
                                </div>
                                <div class="card-text ">
                                    <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor ipsum minima minus
                                        modi nobis quisquam tempora temporibus? Ad aspernatur dolorum maxime nesciunt omnis
                                        reprehenderit suscipit.
                                        </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> -->
            
            <table    class="table table-striped" >
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">First</th>
                        <th scope="col">Last</th>
                        <th scope="col">Handle</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>@mdo</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                        <td>@fat</td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td colspan="2">Larry the Bird</td>
                        <td>@twitter</td>
                    </tr>
                </tbody>
            </table>

            <div class="col-12 ml-2 bg-secondary">
                <h3 class="">Ultimas Notícias</h3>
                <div class="card">
                    <div class="row">
                        <div class="col-3   ml-2">
                            <img src="http://via.placeholder.com/900x500" class="w-100">
                        </div>
                        <div class="col-9">
                            <div class="card-block">
                                <div class="card-title font-weight-bold mb-0">
                                    Lorem ipsum dolor sit amet
                                </div>
                                <div class="card-text ">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor ipsum minima minus
                                        modi nobis quisquam tempora temporibus? Ad aspernatur dolorum maxime nesciunt omnis
                                        reprehenderit suscipit.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <table class="table table-bordered border-primary">

                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">First</th>
                        <th scope="col">Last</th>
                        <th scope="col">Handle</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>@mdo</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                        <td>@fat</td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td colspan="2">Larry the Bird</td>
                        <td>@twitter</td>
                    </tr>
                </tbody>            
            </table>

            <!-- <div class="container-fluid h-50">
                <div class="row h-100">
                    <div class="col-2 n1">1</div>
                    <div class="col-8 n2">
                        <img id="fotoExpandida" class="" src="http://via.placeholder.com/900x500" >
                    </div>
                    <div class="col-2 n1">3</div>
                </div>
            </div> -->

            <!-- <div id="element-to-print">
                <span>I'm on page 1!</span>
                <div class="html2pdf__page-break"></div>
                <span>I'm on page 2!</span>
            </div> -->

            <table class="table table-striped">
        <thead>
            <tr>
                <th>id</th>
                <th>Nome</th>
                <th>Estado</th>
            </tr>
        </thead>
        <tbody>          
   
            <?php            
                foreach ($conexao->query($sql_all) as $row) {
                    echo '
                    <tr>
                        <td>'. $row['id'].'</td>
                        <td>'.$row['nome'].'</td>
                    ';

                    //busca do nome da Região deste estado
                    $sqlRegiao = 'SELECT nome FROM estados  WHERE id = "'.$row['id_uf'].'" ';
                    $resRegiao = $conexao->prepare( $sqlRegiao );
                    $resRegiao->execute();

                    $result = $resRegiao->fetchAll(PDO::FETCH_ASSOC);
                    //echo $result[0]['nome'];

                    echo '
                        <td>'.$result[0]['nome'].'</td>
                    </tr>
                    ';
                }
            ?>            
        </tbody>
    </table>
        </div>

    </div>



   
</body>
</html>